apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "appname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "appname" . }}-db
spec:
  ports:
    - port: 3306
  selector:
    app: {{ template "appname" . }}-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "appname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "appname" . }}-db
      tier: database
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}-db
        tier: database
    spec:
      containers:
        - image: mariadb:10.8
          name: mariadb
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.secretName }}
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.secretName }}
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.secretName }}
                  key: DB_PASSWORD

          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: {{ template "appname" . }}-db
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ template "appname" . }}-db
          persistentVolumeClaim:
            claimName: {{ template "appname" . }}-db
