apiVersion: v1
kind: Service
metadata:
  name: {{ template "appname" . }}-redis-master
  labels:
    app: {{ template "appname" . }}-redis
    role: master
    tier: backend
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: {{ template "appname" . }}-redis
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "appname" . }}-redis-master
  labels:
    app: {{ template "appname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ template "appname" . }}-redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}-redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
